events {}
http {
 server {
  listen 8080;
  location /api/students/ {
   location ~ ^/api/students/[^/]+/schedule$ { proxy_pass http://schedule:8080; }
   proxy_pass http://students:8080;
  }
  location = /api/students { proxy_pass http://students:8080; }
  location /api/teachers { proxy_pass http://teachers:8080; }
  location /api/rooms { proxy_pass http://rooms:8080; }
  location /api/subjects { proxy_pass http://schedule:8080; }
  location /api/lessons { proxy_pass http://schedule:8080; }
  location /swagger { proxy_pass http://schedule:8080; }
  location / { return 404; }
 }
}
